### ISSUE TITLE
Crash when unable to load a plugin

### ISSUE THREAD

**Issue by juzhang** [MusculoskeletalAtlasProject/mapclient#12]
MAP Client crashes with the following except when it fails to load certain plugins. Does not crash with this error for all plugins that fails to load.

> Traceback (most recent call last):
>  File "/home/ju/.local/bin/mapclient", line 11, in <module>
>    sys.exit(winmain())
>  File "/home/ju/.local/lib/python2.7/site-packages/mapclient/application.py", line 105, in winmain
>    window.checkApplicationSetup()
>  File "/home/ju/work_projects/MAP/mapclient/dev/mapclient/src/mapclient/view/mainwindow.py", line 250, in checkApplicationSetup
>    self.showPluginErrorsDialog()
>  File "/home/ju/work_projects/MAP/mapclient/dev/mapclient/src/mapclient/view/mainwindow.py", line 422, in showPluginErrorsDialog
>    if pm.showPluginErrors():
>AttributeError: 'PluginManager' object has no attribute 'showPluginErrors'

The plugin warning prior to the exception was:

> 03/02/2016 - 11:23:12.558 - mapclient.core.managers.pluginmanager - WARNING - Plugin 'vifmscansourcestep' not loaded
> 03/02/2016 - 11:23:12.558 - mapclient.core.managers.pluginmanager - WARNING - Reason: Wrong number of columns at line 6
> 03/02/2016 - 11:23:12.559 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/.local/lib/python2.7/site-packages/mapclient/core/managers/pluginmanager.py", line 291, in load
>     module = import_module(PLUGINS_PACKAGE_NAME + '.' + modname)
> 
> 03/02/2016 - 11:23:12.559 - mapclient.core.managers.pluginmanager - WARNING -   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> 
> 03/02/2016 - 11:23:12.559 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/work_projects/MAP/myplugins/vifmscansourcestep/mapclientplugins/vifmscansourcestep/__init__.py", line 22, in <module>
>     from mapclientplugins.vifmscansourcestep import step
> 
> 03/02/2016 - 11:23:12.560 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/work_projects/MAP/myplugins/vifmscansourcestep/mapclientplugins/vifmscansourcestep/step.py", line 13, in <module>
>     from workutils import load_dicom
> 
> 03/02/2016 - 11:23:12.560 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/work_projects/workutils/load_dicom.py", line 3, in <module>
>     import femur_data
> 
> 03/02/2016 - 11:23:12.560 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/work_projects/workutils/femur_data.py", line 399, in <module>
>     badScans = BadScans()
> 
> 03/02/2016 - 11:23:12.560 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/work_projects/workutils/femur_data.py", line 381, in __init__
>     bs = loadtxt( os.path.join(os.path.dirname(__file__), "scanlists/bad_scans_duane.txt"), dtype=str )
> 
> 03/02/2016 - 11:23:12.560 - mapclient.core.managers.pluginmanager - WARNING -   File "/home/ju/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 925, in loadtxt
>     % line_num)
> 
> Traceback (most recent call last):
>   File "/home/ju/.local/bin/mapclient", line 11, in <module>
>     sys.exit(winmain())
>   File "/home/ju/.local/lib/python2.7/site-packages/mapclient/application.py", line 105, in winmain
>     window.checkApplicationSetup()
>   File "/home/ju/work_projects/MAP/mapclient/dev/mapclient/src/mapclient/view/mainwindow.py", line 250, in checkApplicationSetup
>     self.showPluginErrorsDialog()
>   File "/home/ju/work_projects/MAP/mapclient/dev/mapclient/src/mapclient/view/mainwindow.py", line 422, in showPluginErrorsDialog
>     if pm.showPluginErrors():
> AttributeError: 'PluginManager' object has no attribute 'showPluginErrors'

**Comment by juzhang** [comment]
This is from the latest github commit.
